# Generated by Django 2.2.1 on 2019-05-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Molecule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mass', models.FloatField(default=0)),
                ('reference', models.CharField(max_length=200)),
                ('ccs', models.FloatField(default=0)),
                ('sdf_file', models.CharField(default='none', max_length=50000)),
            ],
        ),
    ]
